service: propreturns-aws-lambda
provider:
  name: aws
  runtime: nodejs18.x
  region: "ap-south-1"
functions:
  app:
    handler: dist/index.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
